import type { Metadata } from "next";
import { DefaultTheme } from "@/components/theme/DefaultTheme";
import { ThemeProvider } from "@mui/material";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<ThemeProvider theme={DefaultTheme}>
				<body>
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
