name: Build Works

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "<Build> Application"

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v6

      - name: <Restore> .next/cache
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        uses: actions/cache@v5
        with:
          path: |
            .next/cache
          key: |
            ${{ github.job }}-${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: <Add> Node/NPM
        uses: actions/setup-node@v6
        with:
          node-version-file: ./.node-version
          cache: npm

      - name: <Install> NPM
        shell: bash
        run: npm ci

      - name: <Lint> front-end
        shell: bash
        run: npm run lint

      - name: <Test> front-end
        shell: bash
        run: npm run test

      - name: <Env> default
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        shell: bash
        run: |
          cp .env.template .env

      - name: <Env> staging
        if: github.ref == 'refs/heads/develop'
        shell: bash
        run: |
          echo "NODE_ENV=production" >> ${GITHUB_ENV}
          echo "#staging" > .env.production
          echo "NEXT_PUBLIC_EXECUTION=staging" >> .env.production
          echo "NEXT_PUBLIC_DEFAULT_STORAGE=local" >> .env.production
          echo "NEXT_PUBLIC_TRACKING=true" >> .env.production
          echo "NEXT_PUBLIC_SCM_VERSION=${{ github.sha }}" >> .env.production

      - name: <Env> production
        #if: github.ref == 'refs/heads/master'
        if: false
        shell: bash
        run: |
          echo "NODE_ENV=production" >> ${GITHUB_ENV}
          echo "#production" > .env.production
          echo "NEXT_PUBLIC_EXECUTION=production" >> .env.production
          echo "NEXT_PUBLIC_DEFAULT_STORAGE=local" >> .env.production
          echo "NEXT_PUBLIC_TRACKING=true" >> .env.production
          echo "NEXT_PUBLIC_SCM_VERSION=${{ github.sha }}" >> .env.production

      - name: <Build> front-end
        shell: bash
        run: npm run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}

      - name: <Artifact> front-end
        uses: actions/upload-pages-artifact@v5
        with:
          path: out

      - name: <Artifact> coverage
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: coverage

  deploy-github-pages:
    name: "<Deploy> Github Pages"
    needs:
      - build

    if: github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: <Deploy> GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
